PKG_NAME=liblc3
PKG_URL=https://github.com/google/liblc3.git
PKG_VERSION=8b3720abce42562bd940d0a4f09e388ddea52fb5
PKG_LICENSE=Apache-2.0

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR)/src -f $(RIOTBASE)/Makefile.base
