PKG_NAME    = nanocbor
PKG_URL     = https://github.com/benpicco/nanocbor
PKG_VERSION = abab4348541cad72da5ec5f0e26f01e74f7cb648
PKG_LICENSE = LGPL-2.1

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR)/src -f $(RIOTBASE)/Makefile.base MODULE=$(PKG_NAME)
