PKG_NAME    = nanocbor
PKG_URL     = https://github.com/benpicco/nanocbor
PKG_VERSION = 6b3249b71b145e34f2d9edce57c26cfd375a67ce
PKG_LICENSE = LGPL-2.1

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR)/src -f $(RIOTBASE)/Makefile.base MODULE=$(PKG_NAME)
