PKG_NAME=esp32_sdk_lib_wifi
PKG_URL=https://github.com/espressif/esp32-wifi-lib
# This is a version in the v4.4.4 release branch
PKG_VERSION=723f180ee199e60983a6e2b5986f645ffed69e99
PKG_LICENSE=Apache-2.0

include $(RIOTBASE)/pkg/pkg.mk

# there is nothing to compile
all:
