PKG_NAME    = codec2lite
PKG_URL     = https://erdgeist.org/gitweb/codec2lite
PKG_VERSION = 9022d768021bbe15c7815cc6f8b64218b46f0e10
PKG_LICENSE = LGPL-2.1

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR) -f $(CURDIR)/$(PKG_NAME).mk
