PKG_NAME=esp32_sdk_lib_phy
PKG_URL=https://github.com/espressif/esp-phy-lib
# This is a version in the v4.4.4 release branch
PKG_VERSION=9a94277c0d8dc1174fc3dd2dcb48dea49e61931d
PKG_LICENSE=Apache-2.0

include $(RIOTBASE)/pkg/pkg.mk

# there is nothing to compile
all:
