PKG_NAME=esp32_sdk_lib_bt_esp32
PKG_URL=https://github.com/espressif/esp32-bt-lib
# This is a version in the v4.4.3 release branch
PKG_VERSION=4b1a62726bc870a701d5b6d7a157bfcc4793a0f8
PKG_LICENSE=Apache-2.0

include $(RIOTBASE)/pkg/pkg.mk

# there is nothing to compile
all:
