include ../Makefile.tests_common

FEATURES_REQUIRED += periph_gpio_irq
FEATURES_REQUIRED += periph_adc
FEATURES_REQUIRED += periph_dac
FEATURES_REQUIRED += periph_timer

USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include
