include ../Makefile.drivers_common

USEMODULE += mtd_flashpage
USEMODULE += mtd_write_page
USEMODULE += embunit

# define an auxiliary slot on the internal flash
SLOT_AUX_LEN := 0x8000

include $(RIOTBASE)/Makefile.include
